### ISSUE TITLE
Import Error: cannot import celery from Celery

### ISSUE THREAD

**Issue by dolarpatel** [FCTL3314/SpecialRecipe#4]
Hi Team,
I have tried all my best and follow your steps from first but when I am tried to run "python manage.py makemigrations". I got error.

Thanks

**Comment by FCTL3314** [comment]
Hi, sorry about that, could you please send me the error you are getting.

**Comment by dolarpatel** [comment]
I got below error while run migration command:

![236051308-2bb786fc-5985-402f-83a5-1140a321427f-png-1366×768-](https://user-images.githubusercontent.com/3885466/236052168-67f76bc2-f14a-4558-9124-1e65c52dcaf8.png)

I followed all the steps and installed all given requirements too.

Thanks.

**Comment by FCTL3314** [comment]
You should open the celery_app file in the core package, and check if the Celery class from the celery library is imported correctly, maybe for some reason you have installed the wrong library(Also check the version of your celery library by running pip freeze, the version should be 5.2.7.), if you can’t fix the class import, then try running the command: pip install - -upgrade pip to upgrade the pip package manager.
![pycharm64_P0QYUNZmtA](https://user-images.githubusercontent.com/97694131/236055257-75db7968-d084-471c-b5a3-432bd83dee35.png)
I just tried to locally deploy the project myself, everything worked out for me, it's strange what caused this problem.

**Comment by dolarpatel** [comment]
I tried as per your request and celery version is same 5.2.7, then I upgraded the pip and again try to run migration it's same error

![image](https://user-images.githubusercontent.com/3885466/236059677-6031f24c-35df-4a87-8aa7-9b6ad7e1cd06.png)

Thanks for your support!

**Comment by FCTL3314** [comment]
I think I found a solution to your problem:

1. https://stackoverflow.com/questions/73933432/django-celery-cannot-import-name-celery-from-celery-after-rebuilding-dockerf

2. https://stackoverflow.com/questions/74025035/importerror-cannot-import-name-celery-from-celery

Seems like this should help.

**Comment by dolarpatel** [comment]
I checked 2. reference and hasn't found anything useful and 1st for docker, so could you please help me in installation.

Thanks in advance.

**Comment by FCTL3314** [comment]
Please tell me your version of python, since I found that this problem occurs on python version 3.7 and some others.

**Comment by dolarpatel** [comment]
> Please tell me your version of python, since I found that this problem occurs on python version 3.7 and some others.

I have 3.7.4

**Comment by dolarpatel** [comment]
Finally, I done Thanks for your help.

**Comment by FCTL3314** [comment]
Was happy to help you!
